on: push

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile protobuf
        run: ./BUILD.sh
        
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 5.0

      - name: Run Unit tests
        run: pytest -v