on: push

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Unit tests
        run: pytest -v